### ISSUE TITLE
Error message when calling __set__

### ISSUE THREAD

**Issue by jhorneman** [i-like-robots/rewireify#11]
I hope this is the right repo.

When I call `__set__` on a module, to mock a function it requires from another module, I get the following error message:

    PhantomJS 1.9.8 (Windows 7 0.0.0) ERROR
      TypeError: 'undefined' is not a function (evaluating 'function (revertArgs) {
              __set__.apply(null, revertArgs);
          }.bind(null, arguments.revertArgs)')

I've made a minimal reproduction repo here: [https://github.com/jhorneman/karma-browserify-repro]().

Just run npm install, then npm run test.

I'm using Karma, Jasmine, Browserify, and Rewireify, under Windows 7.

Please let me know if you need more information.

**Comment by i-like-robots** [comment]
Thanks for setting up the test case, that makes my life much easier! I'll take a look when I can.

**Comment by i-like-robots** [comment]
I haven't had time to set this up yet but looking at the code - have you tried switching `exports` to `module.exports`? Rewireify assigns the `__get__` and `__set__` properties on `module.exports` which takes precedence over `exports` (see [here](http://www.hacksparrow.com/node-js-exports-vs-module-exports.html) for more info).

**Comment by i-like-robots** [comment]
I've had a minute and managed a proper look. Downgrading Rewireify to 0.2.0 in your example app works. This version of Rewireify bundled an old version of the injected `__set__` method from Rewire so this may be a bug may be within the Rewire dependency or Rewireify's integration with it.

**Comment by jhorneman** [comment]
Thanks! (module.exports made no difference.)

By the way, I also added the issue over at Rewire: https://github.com/jhnns/rewire/issues/70

I'm glad there is a workaround at least. I was going crazy since this seemed like such a common use case and I wondered what I was doing wrong.

**Comment by i-like-robots** [comment]
Are you able to run the test runner successfully in your browser (rather than through headless PhantomJS)? Mocking the methods of dependencies is [covered in the test suite](https://github.com/i-like-robots/rewireify/blob/master/test/spec.js#L143-146) and is working as expected when in Chrome and Firefox.

**Comment by jhnns** [comment]
`Function.prototype.bind` is undefined in PhantomJS 1.x (See https://github.com/ariya/phantomjs/issues/13107)

**Comment by i-like-robots** [comment]
Thanks for taking a look @jhnns and figuring it out =D

**Comment by jhorneman** [comment]
Thank you for figuring out what the problem was.
