### ISSUE TITLE
Rewireify exposes __get__ and __set__ via Object.keys

### ISSUE THREAD

**Issue by TheSavior** [i-like-robots/rewireify#13]
Currently with rewireify, `__get__` and `__set__` are part of the returned array when using Object.keys on a module that returns an object.

For example:

```
// foo.js

var Foo = {
  key: 'val'
};

module.exports = Foo;
```

```
var Foo = require('foo');
assert.sameMembers(Object.keys(Foo), ['key', '__get__', '__set__']); 
```

However, I don't want my code to see anything about `__get__` or `__set__`, such that my assert would be:
```
assert.sameMembers(Object.keys(Foo), ['key']); 
```

I ran into this problem when building a port of rewireify for node, and used Object.defineProperty to fix it:
https://github.com/TheSavior/rewire-global/blob/master/index.js

**Comment by TheSavior** [comment]
And this is the test I have for it: https://github.com/TheSavior/rewire-global/blob/master/test/tests/tests.js#L51

**Comment by i-like-robots** [comment]
Thanks for the heads up and sharing your code. This is something I'd considered and forgotten about, I think it's certainly worth adding.

**Comment by TheSavior** [comment]
It's causing one of our tests to fail right now and I'm uncomfortable manually adding __get__ and __set__ to our assertion. What do you believe should be the next steps? I'd be happy to try to put out a PR making rewireify use Object.defineProperty just like rewire-global. Do you agree with that approach?

**Comment by i-like-robots** [comment]
Very happy to accept a PR as my connection is super-flakey over 3G right now!
