### ISSUE TITLE
0.2.3 - methods aren't injected if typeof module.exports is 'function'

### ISSUE THREAD

**Issue by tran2** [i-like-robots/rewireify#16]
In 0.2.3, there's a check `if typeof module.exports === 'object' ` before injecting. 
In some of my codes, ``typeof module === 'object' `` but `` typeof module.exports === 'function' ``
so ``__get__`` and ``__set__`` never gets injected

**Comment by loudwinston** [comment]
I've also encountered this issue.  This changes breaks `rewireify` for anyone exporting a React component in a module, since `React.createClass` returns a function.

My team has reverted to 0.2.2 for now until this issue is resolved.

**Comment by i-like-robots** [comment]
Thanks for reporting this, a fix is imminent

**Comment by i-like-robots** [comment]
Fixed in 059be2bc4ddcac4f69394ccca3b2c4985966c37d
