### ISSUE TITLE
Intermittent error attempting to define __get__ more than once on Karma startup.

### ISSUE THREAD

**Issue by iamrandys** [i-like-robots/rewireify#3]
**Error: Invariant Violation: ReactCompositeComponentInterface: You are attempting to define `__get__` on your component more than once. This conflict may be due to a mixin.**

First off, I do not believe this is a rewireify issue (rewirify has been solid), but from the error message this seems the most logical place for others to look for this issue.

About 1 out of 10 times and only on initial Karma startup, I get the following error and Karma hangs.  It is very hard to troubleshoot the issue since it does not happen all the time.  I am using:

    "karma": "^0.12.21",
    "karma-bro": "^0.6.2",
    "karma-jasmine": "^0.2.2",
    "react": "~0.11.0",
    "reactify": "^0.14.0",
    "rewireify": "~0.0.9",

**Comment by adamdonahue** [comment]
But how is this a fix?  Wouldn't clearing the mixins break the component?

**Comment by joneves** [comment]
The problem does not seem to be solved, rewireify is unusable in its current state as it tried to apply getters and setters mutliple times to mixins.  The solution mentioned above as the error occurs when processing require constructs during initialisation.

**Comment by i-like-robots** [comment]
Could you supply some example code?

Always happy to accept a PR too.

**Comment by joneves** [comment]
I'll see what i can do, is there a way of steubbing out deeply nested components

**Comment by i-like-robots** [comment]
It wouldn't be too hard to add a filter, in terms of actually understanding
the dependency tree I don't know.

**Comment by iamrandys** [comment]
Since my last post we have been ignoring mixins using the rewireify --ignore option in karma. It would be nice to be able to supply a "*-mixin" wildcard to the ignore option though.

I don't see that this is an issue with rewireify. It does what it is suppose to do. It just doesn't play well when testing React components that use mixins.

**Comment by joneves** [comment]
Ok.  Is it possible to set rewire a child component inside a component.

A has child B which has a private var i want to override.

**Comment by i-like-robots** [comment]
I've had a think about this, it would be nice if the `--ignore` option could take an array of glob patterns instead of specific paths.

**Comment by iamrandys** [comment]
I agree this would be really nice.  I could include *mixin and I would have to keep updating this setting.

**Comment by i-like-robots** [comment]
@iamrandys If you'd like you can now pull down https://github.com/i-like-robots/rewireify/pull/9 and see if it meets your needs.

**Comment by iamrandys** [comment]
Oh sweet! I'll definitely will test it out and let you know how it works out. Thanks for the help!

**Comment by i-like-robots** [comment]
Modules can now be ignored via pattern in 69a131a9a9aab1eec4bfc540e7b9da8d4b2dd4c6
